// Declaración de variables
var num1 = 5;
var num2 = 10;

// Operaciones aritméticas
var suma = num1 + num2;
var resta = num1 - num2;
var multiplicacion = num1 * num2;
var division = num1 / num2;
var modulo = num1 % num2;

// Concatenación de strings
var nombre = "Juan";
var apellido = "Pérez";
var nombreCompleto = nombre + " " + apellido;


const numbers = [1, 2, 3, 4, 5];
const doubleNumbers = numbers.map((number) => number * 2);
console.log(doubleNumbers); // Output: [2, 4, 6, 8, 10]

const users = [
  { name: 'John', age: 25 },
  { name: 'Jane', age: 30 },
  { name: 'Bob', age: 35 }